### ISSUE TITLE
Update Question idShort/ShorName/preferredName: now there is also a displayName

### ISSUE THREAD

**Issue by BirgitBoss** [admin-shell-io/questions-and-answers#10]
Update Question "How is the relation between idShort, shortName and preferredName for a submodel element and the related concept description?"
Since Version 4.0RC01 an attribute DisplayName was introduced to referables.
the rules are defined as follows:

If no display name is defined in the language requested by the application, then the display name is selected in the following order if available: 
-	the preferred name in the requested language of the concept description defining the semantics of the element
-	If there is a default language list defined in the application, then the corresponding preferred name in the language is chosen according to this order. 
-	the English preferred name of the concept description defining the semantics of the element
-	the short name of the concept description
-	the idShort of the element

**Comment by StenGruener** [comment]
this is same question as number 44 in execl
