### ISSUE TITLE
How to deal with lack of individual data types for Submodel Element Collections?

### ISSUE THREAD

**Issue by mhmmi** [admin-shell-io/questions-and-answers#101]
In the AAS you define Submodel Elements (simple as well as complex), but no individual data types for them. If we now consider, for example, a complex "location" Submodel Element Collection with simple double properties for the coordinates. Then one must assign individual semanticIds to this kind of construct depending on the usage to allow an individual, context-dependent meaning of the SMEC. Example: A robot has a location SMEC for its base and one for its tool center point. Both should be described by individual semanticIds (i.e., concept descriptions). On the other hand, both describe locations, which should be able to be offset against each other in generic program code (e.g., calculate distance of the locations). How is this possible without a common data type "Location" for both SMEC?

**Comment by zrgt** [comment]
Relevant Issue: https://github.com/admin-shell-io/questions-and-answers/issues/44

**Comment by JoergNeidig** [comment]
18.12.2023 Best Practice Group:
We recommend: 
- Use the individual semanticID for the individual SMC to denote "location at base" or "locaction tool center point"
- Use supplementalSemanticID to descibe for each SMC that it is a "location".
- For the ConceptDescription it is similiar. Create 2 ConceptDescriptions for the individual SMC, and use isCaseOf to reference a 3rd ConceptDescription for "location".
