### ISSUE TITLE
What are the various types of JSON representations for a submodel?

### ISSUE THREAD

**Issue by JS-Aibel** [admin-shell-io/questions-and-answers#115]
What are the various types of JSON representations for a submodel, and what are their use cases?

**API**
Why are the https://admin-shell.io/api/v3.0 JSON response for the endpoints
`GET/serialization?submodelIds={submodelIdentifier}` and `GET/submodels/{submodelIdentifier}` different?

**Package Explorer**
Are any of the API endpoints related to the `Import/Export submodel from JSON` in the Package Explorer?

**Comment by StenGruener** [comment]
Hi Jon,

not really sure about the questions, but from what we see, the serialization endpoint returns an AAS-environment which consists, among others, of an *array* of submodels and also concept descriptoins. The one submodel GET response returns only one submodel, whicle you can define the answer based on parameters, e.g., deep or shallow representation of nested contents.

**Comment by JS-Aibel** [comment]
Hi Sten,

Thank you for the reply.
The question came up because of the question https://github.com/eclipse-basyx/basyx-java-server-sdk/issues/423 for the BaSyx Java SDK AAS Environment.
Since the AAS Environment is following the specification of the AAS Part 2: Application Programming Interfaces, I thought it was better to ask the question here.

**Use case where the difference in response has an impact.**
When using the BaSyx-Python SDK method `read_aas_json_file()`, the json from the `/submodels/` endpoint will not return any objects in the object store. When using the `/serialization` endpoint the method work as expected. 

**Questions**
1. Why is the difference in response breaking the method?
2. Which of the endpoint’s responses corresponds to `Import/Export submodel from JSON` in the Package Explorer?

**Comment by StenGruener** [comment]
Hi, sorry i so dumb to understand what are "object in the object store", are those aux files?

**Comment by JS-Aibel** [comment]
**ObjectStore**
The ObjectStore is provided by the [BaSyx Python SDK](https://github.com/eclipse-basyx/basyx-python-sdk) and can be used as a simple in-memory store for multiple AAS and their shell objects. The SDK has methods for serialization and deserialization of AASs.

**Use case**
Using the methods in the SDK, I tried to read the response from the endpoint `GET/submodels/{submodelIdentifier}`, but it did not work. However, the `GET/serialization?submodelIds={submodelIdentifier}` response was properly read by the SDK method.
This use case seems to show that these endpoints give out distinct JSON response structures.

**Question**
The question boils down to why there are three different JSON structures even though they support the same JSON Schema.

- GET/submodels/{submodelIdentifier} response
- GET/serialization?submodelIds={submodelIdentifier response
- Package Explorer export to JSON

Note: The answer to issue https://github.com/eclipse-aaspe/package-explorer/issues/254 could provide an explanation for the JSON from Package Explorer.

**Comment by JS-Aibel** [comment]
> the serialization endpoint returns an AAS-environment which consists, among others, of an _array_ of submodels and also concept descriptoins. The one submodel GET response returns only one submodel

Your first answer was the solution to the problem with the SDK methods. 
By wrapping the content from the response `GET/submodels/{submodelIdentifier}` in a ‘submodels’ array, the SDK method was able to read it. For the JSON from the Package Explorer, it seems to be missing the attribute modelType. I guess this will be answered in [eclipse-aaspe/package-explorer#254](https://github.com/eclipse-aaspe/package-explorer/issues/254).

Thank you for the help!
