### ISSUE TITLE
Best practice to instantiate a submodel template

### ISSUE THREAD

**Issue by JS-Aibel** [admin-shell-io/questions-and-answers#116]
What is the best practice to instantiate a submodel template that does not have a plugin?

1. Create a submodel manually and use the submodel template as a lookup together with its specification?
2. Export the submodel template to JSON and import it into another AAS. Then, change the kind from template to instance of the copied template and adjust it accordingly?

I feel like method number 2, which seems like the easiest approach, is prone to errors where the template holds dummy values that are overlooked while converting the submodel to an instance.

**Comment by StenGruener** [comment]
Hi, i think this is the way we do when manually using package explorer. Also submodel tempaltes contain some hints about data expected to be in there.
