### ISSUE TITLE
Missing BOM Submodel Examples in FAQ

### ISSUE THREAD

**Issue by JS-Aibel** [admin-shell-io/questions-and-answers#118]
The links to the examples of the BOM submodel in the FAQ answer appear to be broken. Are there any new examples available for using a BOM submodel?

**References**

- FAQ: https://github.com/admin-shell-io/questions-and-answers?tab=readme-ov-file#idgh64 
- Related Issue: https://github.com/admin-shell-io/questions-and-answers/issues/64

**Comment by StenGruener** [comment]
@JS-Aibel, could you check PR #119

**Comment by JS-Aibel** [comment]
Thank you for updating the links, @StenGruener.
The submodel template specification link is working. The Example submodels link goes to the BOM template, not an example of a BOM instance.
