### ISSUE TITLE
attribue "local" in References was removed - update answer

### ISSUE THREAD

**Issue by BirgitBoss** [admin-shell-io/questions-and-answers#12]
Update question "Can semantic ID(s) be used without defining a concept description within the AAS package?"

In V3.0RC01 of part 1 of AAS in Detail the attribue "local" in References was removed.

Minor: correct typo:  pakckage ==> package

**Comment by StenGruener** [comment]
This is question 41

"
Can semantic ID(s) be used without defining a concept description within the AAS package?

Yes. Please use the following alternatives:

type=ConceptDescription, local=True: the concept description is within the package or deployed on the same server like the element referring to it
type=ConceptDescription, local=False: the concept description is located within a different package or possibly deployed on a different server than the element referring to it
type=GlobalReference, local=False: a concept description object is not defined, just a reference to an external source is made
"

So, the first alternative will go away, correct. In this case the AAS-client has to scan through available concept descriptions, correct?

**Comment by StenGruener** [comment]
Can semantic ID(s) be used without defining a concept description within the AAS package?

Yes. Please use the following alternatives:

type=ConceptDescription: 2 cases: 1) the concept description is within the package or deployed on the same server like the element referring to it and 2) the concept description is located within a different package or possibly deployed on a different server than the element referring to it
type=GlobalReference: a concept description object is not defined, just a reference to an external source is made
