### ISSUE TITLE
How to define the relationship between asset instance and asset type and the corresponding submodels

### ISSUE THREAD

**Issue by BirgitBoss** [admin-shell-io/questions-and-answers#13]
Extracted from #7  for easier tracking

• Zurzeit gibt es keine eindeutige Referenz zwischen Asset Instanz und Asset Type. Ähnlich wie die SemanticId bei der Submodel Instanz Template Referenzierung. Relationship ist nicht ausreichend, da diese von der Bedeutung nicht spezialisiert auf Typ/Instanzbeziehung ist. Man kann zwar auf der AAS Ebene mit dem Attribute „derivedFrom“ deren Beziehung darstellen. Das entspricht aber nur einer impliziten nachvollziehbaren, d.h. maschineninterpretierbaren Beziehung.

• Es gibt prinzipiell zwei verschiedenen Submodel Modelle eine für den Assettyp und einen für die Assetinstanz (Beispiel Typ kann für Properties Ranges angeben, für die Instanz gibt es dann konkrete Werte). Es sollten deshalb auch 2 Submodell, für ein konkretes Asset geben, die aufeinander verweisen. Die Unterscheidung wird maschineinterintertierbar, ob sich ein Submodel in einer AAS steckt, die auf ein Assettyp oder Assetinstanz verweist. Das ist wieder eine implizite Beziehungsart.
 es müsst eine semantische, d.h. maschineinterpretierbare Identifikation geben, ob ein Submodel für Typ oder Instanz gültig is

**Comment by BirgitBoss** [comment]
https://github.com/admin-shell-io/questions-and-answers/issues/7#issuecomment-716809634

**Comment by BirgitBoss** [comment]
see also admin-shell/aasx-package-explorer/issues/38

**Comment by BirgitBoss** [comment]
One solution might be to add an optional assetType attribute to AssetAdministration/AssetInformation. The value corresponds to the globalAssetId of the Asset Type.

**Comment by StenGruener** [comment]
revisit on 14.06.21:
- what about qualifier on submodel level? e.g. assetTypes?

**Comment by StenGruener** [comment]
Q: How to define the relationship between asset instance and asset type wrt. corresponding submodels.
A: For AAS, the relation "derivedFrom" should be used. For assets themselves, no such relation is currently available in the meta-model.
