### ISSUE TITLE
How does the version of a submodel impacts referencing of a submodel?

### ISSUE THREAD

**Issue by BirgitBoss** [admin-shell-io/questions-and-answers#14]
Extracted from #7  for easier tracking

Submodel Template Versionierung
o Die Versionierung bei einem Template ist zwingend erforderlich und sollte am Ende der SemanticId erfolgen
o Verallgemeinerung: müsste nicht bei allen Referenzen eine Version mitgegeben werden können?
o Vorschläge IRI wie IRDI mit Version/Revision ausstatten
• In die ReferenzType Definition Version/Revision aufnehmen
• Version/Revision in die IRI strukturell aufnehmen

**Comment by BirgitBoss** [comment]
https://github.com/admin-shell-io/questions-and-answers/issues/7#issuecomment-716810708:

**Comment by StenGruener** [comment]
recheck: 14.06.
- "Versioning within semantic id e.g. "https://github.com/admin-shell-io/id/tree/master/DataSpecificationTemplates/DataSpecificationIEC61360/ **2/0**": 
-- Breaking semantic changes, i.e., other meaning
-- Possibly, complete break of external-interface
-- Not clarified yet which meaning "major" and "minor" parts within the semantic ID are having. Currently they correspond to the version of the submodel spec e.g. 2.0 or 2.1.
- Changes within "administrative information" within AAS
-- Related to content within AAS, not to its "external-interface", therefore not necessary to standardize meanings of Major/Minor at this point in time.

**Comment by StenGruener** [comment]
How does the version of a submodel impacts referencing of a submodel?

"Versioning within semantic id e.g. for URIs "0173-xxx-zzz-zzz#version" or "https://admin-shell.io/sandbox/zvei/nameplate/0/1/Nameplate":
-- Possibly, breaking semantic changes, i.e., other meaning
-- Possibly, reverse-compatibility, e.g. extension
-- Not clarified yet which meaning "major" and "minor" parts within the semantic ID are having. Currently they correspond to the version of the submodel spec e.g. 2.0 or 2.1.

Changes within "administrative information" within AAS:
-- Related to content within AAS, not to its "external-interface", therefore not necessary to standardize meanings of Major/Minor at this point in time.

As of now, references ignore versioning information. In case versioning is essential, the versioning information must be part of the element's ID.
