### ISSUE TITLE
How to treat ECLASS Quantity Concept in AAS?

### ISSUE THREAD

**Issue by aorzelskiGH** [admin-shell-io/questions-and-answers#25]
![image](https://user-images.githubusercontent.com/48956800/104178633-f7e02480-540a-11eb-9ccf-7ac15bd5256e.png)

**Comment by BirgitBoss** [comment]
The metamodel of the AAS (status: V3.0RC01) does not explicitly support the concept of quantities. This means, in case properties are not defined in ECLASS or in any other standardized dictionary it is not possible to specify the quantity of this proprietary property. In case the property is defined in ECLASS then the quantity is defined in ECLASS itself but the corresponding IRDI is not available in the AAS serialization.
Future versions of the AAS might support quantities:
1) by IRDI reference only in the concept descriptions of property
2) by providing a corresponding data specification for quantieis conformant to IEC61360
