### ISSUE TITLE
How to define optional and mandatory elements for a submodel of Kind=Template?

### ISSUE THREAD

**Issue by aorzelskiGH** [admin-shell-io/questions-and-answers#26]

**Comment by StenGruener** [comment]
question 43 from legacy excel

**Comment by StenGruener** [comment]
I propose to take mandatory/optional qualifiers from AAS submodel templates used by AAS package Explorer.
![image](https://user-images.githubusercontent.com/69786685/131991210-61830fb6-2659-43f0-b8a3-e1650ac83b03.png)
So the qualifier name is "Multiplier" and values are "One", "ZeroToOne", "ZeroToMany", "OneToMany"

**Comment by StenGruener** [comment]
06.09: make a statement of a "temporary workaround", a clean solution will be provided by Plattform later
