### ISSUE TITLE
How to deal with "property values" that include multiple values?

### ISSUE THREAD

**Issue by JoergNeidig** [admin-shell-io/questions-and-answers#36]
How to deal with "property values" that include a set of values, e.g. seperated by comma? Examples are colors in rgb, coordinates, etc. Is there a specific format for these property elements? How can one transport that a specific format is required?
Could one use the formula qualifier as RegEx to describe the allowed format? What about more complex property values, i.d structs?

**Comment by StenGruener** [comment]
6.9.21: still open

**Comment by StenGruener** [comment]
04.10.2021: current discussion in der UAG VWS, on hold until @BirgitBoss will update us with a decision.

**Comment by StenGruener** [comment]
01.08.2022: Currently multi-value properties are not available in the metamodel.
