### ISSUE TITLE
derivedFrom for marking a submodel kind=instance that is derived from a submodel kind=template

### ISSUE THREAD

**Issue by JoergNeidig** [admin-shell-io/questions-and-answers#37]
A clear definition/guide on how to use the derivedFrom-association when referencing that a submodel kind=instance has been derived from a submodel kind=template.
Maybe it should be discussed what is needed to model this relationship: reference via semanticID, derivedFrom, instanceOf, ...? The semantic of derivedFrom should be clearly defined. Does it include instanceOf?
Should be discussed together with the requirements for template descriptions.

**Comment by BirgitBoss** [comment]
There is not derivedFrom association between submodels of kind=instance and kind=template. 

The relationship "derivedFrom" can be established between AAS for an Asset with assetKind=Instance and AAS for an AssetKind=Type.

**Comment by StenGruener** [comment]
Any decision made here @BirgitBoss @JoergNeidig?

**Comment by StenGruener** [comment]
06.09.21: submodel with kind=instance and kind=template should have same semanticID to indicate the applicability of the template
