### ISSUE TITLE
Example needed for a CD with a isCaseOf reference

### ISSUE THREAD

**Issue by StenGruener** [admin-shell-io/questions-and-answers#39]
question 46 in excel

**Comment by BirgitBoss** [comment]
See https://github.com/admin-shell-io/questions-and-answers#id34 for one example how to use isCaseOf (ECLASS And IEC CDD Properties shall be referenced at the same time)

**Comment by StenGruener** [comment]
@degoell could you please provide the AAS with an example? + add a second isCaseOf relation to 0112/2///61987#ABA565
