### ISSUE TITLE
Example needed for valueID on an ECLASS example

### ISSUE THREAD

**Issue by StenGruener** [admin-shell-io/questions-and-answers#40]
question 46 from excel

Practicioners need an example for use a valueID of an some ECLASS enum, e.g. a color

**Comment by BirgitBoss** [comment]
Example: 
02-BA975 degree of protection
and valueId 07-WAA046 for value IP65

Note: when implementing the ECLASS/IEC Importer into the AASX Package Explorer it was discussed that it is not the string "IP65" that is the value but the number defined in ECLASS
