### ISSUE TITLE
Where do I find standardized submodel templates?

### ISSUE THREAD

**Issue by aorzelskiGH** [admin-shell-io/questions-and-answers#41]
When an overview page of submodel templates is available, revise the following topic:
[Which names are already defined for important submodels?](#id12)

**Comment by StenGruener** [comment]
See also question 12 https://github.com/admin-shell-io/questions-and-answers#id12

**Comment by alw-iwu** [comment]
Are there machine-readable files from official sources that implement these submodel templates? Also considerations about formats would be interesting:
1. AAS, serialized as AASX, JSON, XML etc.
2. JSON-Schema, XSD to perform validation against.

**Comment by StenGruener** [comment]
@alw-iwu Currently, a publicly available repository of sub-model templates as AASX files is being prepared by IDTA. We are not aware of any automatic validation implementations.
