### ISSUE TITLE
Asset Typerkundung

### ISSUE THREAD

**Issue by ChristianDiedrich-42** [admin-shell-io/questions-and-answers#47]
Asset-Typerkundung mit der AAS

Beschreibung der Asset-Typerkundung: 
Die I4.0-Verwaltungsschale unterscheidet beim repräsentierten Asset zwischen Typ und Instanz. Dabei sagt ein Typ aus, dass das Asset noch nicht existiert, sondern sich innerhalb seines Lebenszyklus noch als Modell vor der Produktion befindet. Instanz wird es mit der Produktion. 
Informationen über die Art des Produkts beinhaltet das Metamodell der Verwaltungsschale nicht. Es ist nicht möglich, über die AssetInformation einer Asset-Instanz auf den Produkttypen zu schließen. 

Beschreibung des Use-Cases: 
Ein Anwender möchte sein Netzwerk nach Assets eines bestimmten Typs erkunden, z.B. Typ Kreiselpumpe. 

Es gibt kein Attribut zum Asset-Typ in der AssetInformation.
 
Das Metamodell der Verwaltungsschale nach AASiD part 1 bietet die Möglichkeit, das Asset zu identifizieren. Es bietet aber keine Möglichkeit, den Typen des Assets also den Produkttypen auszuzeichnen.  

Kein Interface zur Typerkundung: 
In AASiD part 2 werden Interfaces für den Zugriff auf die Informationen einer AAS spezifiziert. Zur Erkundung eines Netzwerks nach Verwaltungsschalen sind folgende Interfaces definiert: 
-	GetAllAssetAdministrationShells
-	GetAllAssetAdministrationShellsById
-	GetAllAssetAdministrationShellsByAssetId
-	GetAllAssetAdministrationShellsByIdShort
-	GetAllAssetAdministrationShellIdsByAssetId 
Zum Auffinden der AAS-Deskriptoren sind folgende Interfaces definiert: 
-	GetAllAssetAdministrationShellDescriptors
-	GetAllAssetAdministrationShellDescriptorsById
Zum Auffinden der Teilmodelle und Teilmodellelemente gibt es die Möglichkeit, sie über die jeweilige Semantic-ID zu finden: 
-	GetAllSubmodelsBySemanticId
-	GetAllSubmodelElementsBySemanticId

Vorschlag zur Umsetzung der Asset-Typerkundung: 
Den Produkttypen eines Assets könnte man der AssetInformation als zusätzliches Attribut hinzufügen, indem man analog zur Ausprägung bei Teilmodellen und Teilmodellelementen durch HasSemantics eine Referenz auf einen Asset-Typen ermöglicht. So könnte beispielsweise der Asset-Typ „Kreiselpumpe“ durch eine Referenz auf ECLASS oder eine andere externe Ontologie referenziert werden. 
Dadurch könnte ermöglicht werden, dass die Interfaces bzgl. der Erkundung von Verwaltungsschalen um folgende Funktion ergänzt werden: 
-	GetAllAssetAdministrationShellsBySemanticId

**Comment by BirgitBoss** [comment]
Hallo Christian, die letzte API-Operation soll wohl eher

•GetAllAssetAdministrationShellsByAssetTypeId

heissen. Bislang haben wir nur die "derivedFrom"-Beziehung zwischen AAS, die u.a. für diese Beziehung verwendet werden sollte.
Das muss in der ARbeitsgruppe zur Verwaltungsschale diskutiert werden.

**Comment by ChristianDiedrich-42** [comment]
Liebe Birgit,

wollen wir miteinander reden, oder wollt Ihr erst intern diskutieren.

Gruß
Christian

Von: Birgit Boss ***@***.***>
Gesendet: Freitag, 30. April 2021 18:59
An: admin-shell-io/questions-and-answers ***@***.***>
Cc: Diedrich, Christian, Prof.Dr. ***@***.***>; Author ***@***.***>
Betreff: Re: [admin-shell-io/questions-and-answers] Asset Typerkundung (#47)


Hallo Christian, die letzte API-Operation soll wohl eher

•GetAllAssetAdministrationShellsByAssetTypeId

heissen. Bislang haben wir nur die "derivedFrom"-Beziehung zwischen AAS, die u.a. für diese Beziehung verwendet werden sollte.
Das muss in der ARbeitsgruppe zur Verwaltungsschale diskutiert werden.

**Comment by StenGruener** [comment]
Forwarded: Birgit will take it to sub working group AAS of AG1 for further discussions
