### ISSUE TITLE
Security under AAS

### ISSUE THREAD

**Issue by Sandeep-sreekumar** [admin-shell-io/questions-and-answers#5]
Can you provide an example AAS file with a security block ? An example for simple RBAC and a example showing ABAC in a AAS sample would be helpful?

**Comment by BirgitBoss** [comment]
In the following documebnt examples and more background information on attribute access control and access control in general can be found:

„Access control for Industrie 4.0 components for application by manufacturers, operators and integrators“, Plattform Industrie 4.0, Discussion Paper, Sept. 2019 (German Version Nov. 2018), [Online]. Available:  [https://www.plattform-i40.de/PI40/Redaktion/EN/Downloads/Publikation/Access%20control%20for%20Industrie%204.0%20components.htm](https://www.plattform-i40.de/PI40/Redaktion/EN/Downloads/Publikation/Access%20control%20for%20Industrie%204.0%20components.html)

**Comment by BirgitBoss** [comment]
see also admin-shell-io/aasx-package-explorer/issues/316
