### ISSUE TITLE
Discuss Endpoint Reference in AAS specification

### ISSUE THREAD

**Issue by StenGruener** [admin-shell-io/questions-and-answers#52]
Issue brought in by JN

Torben Miny (@TorbenD), Thomas Uesländer: DIN Spec examples?
@sebastiankb: WoT examples

![image](https://user-images.githubusercontent.com/69786685/132213138-91f31695-b632-4050-b722-30d2ebf9d95c.png)

**Comment by sebastiankb** [comment]
I had a discussion with Prof. Diedrich and some of his colleagues and it seems that the intention of the endpoint definition here is only to use it for the description of the AAS Type-2 interface and not for the asset itself. I just want to double check with you if this is correct?

**Comment by StenGruener** [comment]
04.10.2021: concluded: quoted structures from REST API are for AAS "northbound" communication. Origin of the structures is from DIN SPEC 16593-1 (currently WIP). In the current document revision it is stated, that the focus of the DIN SPEC is on "ip-based communication", without industrial communication busses and legacy 4-20mA devices.

**Comment by StenGruener** [comment]
21.02.2022: There is an IDTA working group "Asset Interface" with the following scope:
 “Standardization of the structure and semantics required to interact with an asset or service, e.g., to request/subscribe to specific data points or to perform operations based on communication protocols such as Modbus, OPC UA, HTTP, and MQTT. The W3C Web of Things Thing Description is considered to have a base line for content and structure for submodule definition. ".
