### ISSUE TITLE
How to model information for communication to asset (southbound), e.g. for device on-boarding?

### ISSUE THREAD

**Issue by JoergNeidig** [admin-shell-io/questions-and-answers#53]
Consider scenarios in which property values contain up-to-date actual/meassured values, i.e. the AAS acts as a gateway for online runtime data of the asset. An exemplary use case could work as follows:
1) Device manufacturer supplies AAS for the asset which includes the device's connectivity information
2) Integrator imports AAS into his automation engineering system and has now the necessary connectivity info to 
3) Integrator provides northbound server for online device data based on properties (including semanticID, etc.)
4) In case of device change northbound application stays unchanged, but southbound to connectivity has to be re-engineered based on new device AAS.

The connectivity information should include:
a) Devicespecific communication endpoints: E.g. Protocol, DeviceName, Port, ...
b) For each property information necessary to uniquly address the information on the device: E.g. variable name, address/register, data length, device specific data type, acquisition mode, acquisition cycle, access mode, ...
c) An information that clearly identifies the respective properties as an "online" properties

Currently different approaches have been published:
1) Qualifier to model above informations for each property (very informal, not standardised)
2) Model each property as collection, which includes the actual property and additional properties which model the above information (complicated to parse, since for each property one has to check the environment)
Additionally, it has been proposed to enrich the property attributes to include the information b) (e.g. through templates additional to the IEC61360template, maybe even multiple inheritence in concept descriptions.)

Which approach should be used to guarentee multi-vendor-compability?

**Comment by StenGruener** [comment]
20.09.2021: Could we have an example of referencing an OPC UA variable by means of a) an endpoint description and b) a nodeId of the variable and c) ??

**Comment by StenGruener** [comment]
04.10.2021: @aorzelskiGH: could you please provide us with a screenshot/AAS example with an OPC UA variable reference you presented a while ago. 
@sebastiankb: will present an overview of WoT-TD on 18.10.2021

**Comment by StenGruener** [comment]
@sebastiankb

**Comment by sebastiankb** [comment]
The recently formed "Asset Interface Description" working group deals with this use case and tries to find the best place in the AAS model to provide the metadata needed, eg, to subscribe runtime data of an asset.

**Comment by GoetzGoerisch** [comment]
How are you taking OPC 10000-21 here into account?

**Comment by StenGruener** [comment]
closed as part of the working group scope
