### ISSUE TITLE
How to correctly match semanticIds?

### ISSUE THREAD

**Issue by mmarseu** [admin-shell-io/questions-and-answers#54]
As far as I understand, AAS clients are expected to access submodel elements not by matching their idShorts but by their semanticId. However, the semantics of semanticIds and concept descriptions aren't sufficiently clear to me to come up with an algorithm to match elements by semanticId.

I'll be using this heavily cut-down JSON serialization as an example to illustrate my problem:

```json
{
  "submodels": [
    {
      "idShort": "FirstSubmodel",
      "semanticId": {
        "keys": [
          {
            "type": "GlobalReference",
            "idType": "IRI",
            "value": "https://ex.org/niceConcept"
          }
        ]
      }
    },
    {
      "idShort": "SecondSubmodel",
      "semanticId": {
        "keys": [
          {
            "type": "ConceptDescription",
            "idType": "IRI",
            "value": "https://ex.org/niceConcept"
          }
        ]
      }
    },
    {
      "idShort": "ThirdSubmodel",
      "semanticId": {
        "keys": [
          {
            "type": "ConceptDescription",
            "idType": "IRI",
            "value": "https://ex.org/goodConcept"
          }
        ]
      }
    },
  ],
  "conceptDescriptions": [
    {
      "idShort": "NiceConcept",
      "identification": {
        "idType": "IRI",
        "id": "https://ex.org/niceConcept"
      },
      "isCaseOf": []
    },
    {
      "idShort": "GoodConcept",
      "identification": {
        "idType": "IRI",
        "id": "https://ex.org/goodConcept"
      },
      "isCaseOf": [
        {
          "keys": [
            {
              "type": "GlobalReference",
              "idType": "IRI",
              "value": "https://ex.org/niceConcept"
            }
          ]
        }
      ]
    }
  ]
}
```

Given this example, I'm searching for two semanticIds: `https://ex.org/niceConcept` and `https://ex.org/goodConcept`.
The following table lists my current assumptions. Are these correct and what about the unclear cases?

|              | [IRI] https://ex.org/niceConcept | [IRI] https://ex.org/goodConcept
| --------- | ---------------------------------- | ---------------------------------
| FistSubmodel       |  Match | No Match
| SecondSubmodel | Unclear. The referenced concept description has the correct id, but its _isCaseOf_ is empty. | No Match
| ThirdSubmodel     | Match | Unclear. The referenced concept description has the correct id, but its _isCaseOf_ lists a different id.

**Comment by StenGruener** [comment]
Hi @mmarseu, 

Thank you for the cool question!

Our _current working assumption_ is:

left side; match, id of the CD is the same as the semantic id when used as "GlobalReference"
right side: match, since isCaseOf is an "alternative" or "derived" definitions

We will check with futher experts and give you updates.

**Comment by BirgitBoss** [comment]
In V3.0RC02 a new chapter dealing with matching semanticIds will be included. The is-Case-of-attribute is not yet considered, I will submit this as a finding. In general matching can be much more advanced when taking external ontologies into account. Especially when using capabilities.

**Comment by mmarseu** [comment]
Great news, thank you very much. I'm looking forward to the new release, then.

**Comment by StenGruener** [comment]
proposal: put on hold until V3.0RC02

**Comment by BirgitBoss** [comment]
> 
> 
> Given this example, I'm searching for two semanticIds: `https://ex.org/niceConcept` and `https://ex.org/goodConcept`.
> 
> The following table lists my current assumptions. Are these correct and what about the unclear cases?
> 
> 
> 
> |              | [IRI] https://ex.org/niceConcept | [IRI] https://ex.org/goodConcept
> 
> | --------- | ---------------------------------- | ---------------------------------
> 
> | FistSubmodel       |  Match | No Match
> 
> | SecondSubmodel | Unclear. The referenced concept description has the correct id, but its _isCaseOf_ is empty. | No Match
> 
> | ThirdSubmodel     | Match | Unclear. The referenced concept description has the correct id, but its _isCaseOf_ lists a different id.

I do not understand why missing isCaseOf information should have any impact on the matching. For me SecondSubmodel matches niceConcept: the IDs are identical. Same for ThirdSubmodel and goodConcept.

**Comment by mmarseu** [comment]
Interesting, thank you. You're saying that a matching id on the concept description is always enough to constitute a match with the concept, disregarding the presence of any references in *isCaseOf*?

By extension, that means if I'm looking for a specific semantic concept (e.g. `https://ex.org/niceConcept`) and I find an element with that IRI, it doesn't even matter whether the semanticId is a *GlobalReference* or a *ConceptDescription*. It will always be a match.

What I'm really looking for is a flowchart of the matching algorithm. Hoping something like that could be added to v3.0.

**Comment by StenGruener** [comment]
5.4.6 Matching Strategies for Semantic Identifiers
in DotAAS

**Comment by StenGruener** [comment]
**[How to correctly match semantic IDs?](#ghid54)** <a id="ghid54"></a>

Please refer to section "5.4.6 Matching Strategies for Semantic Identifiers" with DotAAS specification (we used v3.0RC02) for IRDI-based strategies.

**Comment by StenGruener** [comment]
consensus 15.08.2022: isCaseOf has no impact on semantic equivalence and can be ignored for automatic matching strategies.

**Comment by StenGruener** [comment]
Since AasDot v3.0 RC2 semanticId has always to have "GlobalReference" type, so no direct reference to a ConceptDescription is possible

**Comment by StenGruener** [comment]
in general String.Equals should be used to check semantic equivalence. A exception is encoding/decoding using Base64-URL encoding for interacting with the REST API.

**Comment by mmarseu** [comment]
> consensus 15.08.2022: isCaseOf has no impact on semantic equivalence and can be ignored for automatic matching strategies.

This simplifies things. Will this be explicitly stated in the next version?

> Since AasDot v3.0 RC2 semanticId has always to have "GlobalReference" type, so no direct reference to a ConceptDescription is possible

Where does it say that? What I'm seeing in RC2 is a recommendation but no requirement.

![image](https://user-images.githubusercontent.com/47556460/184632444-f97a4ab8-fc9e-4557-ac1b-fb34486e732a.png)

How do you link an element to a concept description, then?

> in general String.Equals should be used to check semantic equivalence. A exception is encoding/decoding using Base64-URL encoding for interacting with the REST API.

Alright, but care must be taken regarding case-sensitivity whenever URIs are used as identifiers. The `scheme` and `host` part of a URI are case-insensitive, whereas the `path` is case-sensitive.

**Comment by BirgitBoss** [comment]
You are right, it is not required that it is an external reference.
The idea is that if you have a semantic ID you have several possibilities to find the concept definition:
- search in a local concept dictionary using AAS metamodel
- search in corresponding external dictionary like ECLASS
If the ID is identical the information returned shall be the same.

**Comment by StenGruener** [comment]
Answer proposal: semanticIDs should be checked based on string equivalence. Local and global references are not relevant for the comparison. isCase of is also irrelevant for the comparison. Please note that semantics is a broad topic to discuss and in general semantics are context-sensitive.

**Comment by StenGruener** [comment]
to finalize
