### ISSUE TITLE
Using RDF as an interchange format

### ISSUE THREAD

**Issue by hvags** [admin-shell-io/questions-and-answers#59]
RDF in the form of Turtle files is presented in the documentation as one option for presentation of AAS data for semantic purposes. However the "Details of the Asset Administration Shell" document refers to the AAS serializations packaged in an AASX file as "either json or xml". I would be interested in knowing if this is intentional or if RDF/Turtle should be considered equal to json or xml for exchange purposes.

**Comment by StenGruener** [comment]
15.11.2021: according to "Details of the Asset Administration Shell" mapping to RDF is defined and possible. However, AASX Package Explorer and AASX Server do not support RDF encoding. However, RDF encoding is supported by https://github.com/admin-shell-io/java-serializer.

**Comment by BirgitBoss** [comment]
We consider rdf to be a suitable format for more enhanced applications, e.g. requiring complex queries. So it is just that the focus is a little bit different when to use which format.

**Comment by hvags** [comment]
Thank you both for your feedback. One more question I had regarding this is whether the serialization/deserialization to/from RDF/Turtle is lossless. That is, does the RDF data model support all structures in the AAS or are there any caveats there?

Also @StenGruener - am I wondering if your 'todo' tag means we'll be seeing the rdf serialization  implemented in C# within the AASX Package Explorer / Server repos in

**Comment by StenGruener** [comment]
@hvags 'todo' in this repository means to add this question to the FAQ ;)

Leaving the the answer to the main question to more knowledgeable colleagues.

**Comment by alw-iwu** [comment]
When using the java-serializer and java-model in conjunction, the de/serialization is lossless. The spec (V3RC01) was slightly unclear in some instances but the implementation has ensured completeness.

**Comment by StenGruener** [comment]
@BirgitBoss @MichaelHoffmeisterFesto could you confirm the statement about "lossless conversion" or name anyone who is able to answer?

**Comment by BirgitBoss** [comment]
> When using the java-serializer and java-model in conjunction, the de/serialization is lossless. The spec (V3RC01) was slightly unclear in some instances but the implementation has ensured completeness.

@alw-iwu could you please let us know what was unclear so that we can make the spec. more precise. Thank you!

**Comment by BirgitBoss** [comment]
> @BirgitBoss @MichaelHoffmeisterFesto could you confirm the statement about "lossless conversion" or name anyone who is able to answer?

As @alw-iwu stated: it is "lossless". If it is not, I would consider it a bug.
@sebbader : what do you say?
