### ISSUE TITLE
Qualifiers in AAS

### ISSUE THREAD

**Issue by Sandeep-sreekumar** [admin-shell-io/questions-and-answers#6]
Could you provide some practical examples of using Qualifiers under Submodel elements?

**Comment by BirgitBoss** [comment]
The aasx package explorer provides some predefined standardized qualifiers that can be directly used. There is not yet a document explaining how to use the qualifiers besides the standards themselves the qualifiers were extracted from.
So yes, good examples are still missing and should be provided.

**Comment by StenGruener** [comment]
fixed in 825863149e3070c99da3460eef67459b60f628ed
