### ISSUE TITLE
AAS Registries for Submodel Templates and Instances

### ISSUE THREAD

**Issue by StenGruener** [admin-shell-io/questions-and-answers#62]
Q: Is there a way to determine submodel kind (i.e., Template or Instance) from a Registry without loading the actual submodel from via AAS-repository API?
A: Currently submodel kind can not be retrieved using Registry-API. We propose to maintain a dedicated registry for submodel Templates.

**Comment by StenGruener** [comment]
@BirgitBoss: can this discussion be checked within the UAG?

**Comment by BirgitBoss** [comment]
I will put it to the agenda next year. But I agree: you should not mix AAS instances (or Submodel instances) and Submodel Templates in a single registry/repository. The requirements are very different.

**Comment by StenGruener** [comment]
Cleaned up text proposal for now:
Q: Is it possible to determine submodel kind (i.e., Template or Instance) from a Registry without loading the actual submodel from via AAS-repository API?
A: Currently submodel kind can not be retrieved using Registry-API. This issue will be addressed by standardization working groups. In the meantime, we propose to maintain a dedicated registry for submodel templates within the AAS-infrastructure.
