### ISSUE TITLE
Any examples of using a BOM submodel?

### ISSUE THREAD

**Issue by imcardle** [admin-shell-io/questions-and-answers#64]
Does anyone have an example of using a BOM submodel to create an AAS for a product/machine which comprises several other assets?  If you could share such an example with me that would be much appreciated.

**Comment by alw-iwu** [comment]
Has there been standardization for this? If yes, I'd be interested as well. As of now I have just created a Submodel with a single SMC (SML in V3RC02-terms) with Entity-SMEs.

**Comment by StenGruener** [comment]
@imcardle, are you aware of this paper: https://www.plattform-i40.de/IP/Redaktion/EN/Downloads/Publikation/AAS_Reference_Modelling.pdf?__blob=publicationFile&v=5 ? Examples are available here: http://liabroker.ddns.net:51001/

**Comment by imcardle** [comment]
@StenGruener - No, I was not aware of that paper, or the nice examples that you mentioned!  Thank you very much - I will take a look at them.

**Comment by StenGruener** [comment]
Great, please keep us in the loop in case of positive or negative findings!

**Comment by StenGruener** [comment]
@vojanbe could you please add a reference to IDTA-WG?

**Comment by StenGruener** [comment]
https://industrialdigitaltwin.org/en/content-hub/submodels "Bill of Material" working group

**Comment by StenGruener** [comment]
Q: Is there an example using a Bill of Material (BOM) submodel to create an AAS for a product/machine which comprises several other assets? 
A: An example of modeling is provided in the following publication: https://www.plattform-i40.de/IP/Redaktion/EN/Downloads/Publikation/AAS_Reference_Modelling.pdf?__blob=publicationFile&v=5 ? Examples are available here: http://liabroker.ddns.net:51001/. **Note:** currently the specification of BOM submodel is ongoing within IDTA'  "Bill of Material" working group (reference available here: https://industrialdigitaltwin.org/en/content-hub/submodels ).
