### ISSUE TITLE
What are the semantic features of AASX Package Explorer?

### ISSUE THREAD

**Issue by imcardle** [admin-shell-io/questions-and-answers#65]
It is useful to know about the special features in AASX Package Explorer, such as the BOM graphical view which shows the parent/child relationships between the parts of the BOM.  This feature can be used by setting the sematic ID of a sub-model equal to the value "http://example.com/id/type/submodel/BOM/1/1" - but it seems like you have to know this value exists in order to make use of it!

Some of the papers I've seen suggest that there are other features that can be invoked in a similar way (e.g. the Technical Datasheet sub-model).  Where can I find a list of all these features?

**Comment by StenGruener** [comment]
@imcardle: would you please reference this question to https://github.com/admin-shell-io/aasx-package-explorer/ repo. We are aware of those https://github.com/admin-shell-io/aasx-package-explorer/search?l=JSON&q=AllowSubmodelSemanticId + documentation submodel (no info in json).
