### ISSUE TITLE
Is there a complete list of sub-model templates?

### ISSUE THREAD

**Issue by imcardle** [admin-shell-io/questions-and-answers#66]
Is there a complete list of named sub-model templates somewhere?  The Q&A includes some of them (like Nameplate, for example) but there seem to be others that are missing e.g. MCAD and Service.

**Comment by StenGruener** [comment]
@imcardle there is a list of submodels coming from IDTA (please scroll to the bottom of the page): https://industrialdigitaltwin.org/en/content-hub

**Comment by BirgitBoss** [comment]
> @imcardle there is a list of submodels coming from IDTA (please scroll to the bottom of the page): https://industrialdigitaltwin.org/en/content-hub. Github links are currently referring to a dummy repo, but IDTA is working on it.

GitHub now public, links are working
