### ISSUE TITLE
Requests from project VWS vernetzt

### ISSUE THREAD

**Issue by ChristianDiedrich-42** [admin-shell-io/questions-and-answers#7]
•	Zurzeit gibt es keine eindeutige Referenz zwischen Asset Instanz und Asset Type. Ähnlich wie die SemanticId bei der Submodel Instanz Template Referenzierung. Relationship ist nicht ausreichend, da diese von der Bedeutung nicht spezialisiert auf Typ/Instanzbeziehung ist.  Man kann zwar auf der AAS Ebene mit dem Attribute „derivedFrom“ deren Beziehung darstellen. Das entspricht aber nur einer impliziten nachvollziehbaren, d.h. maschineninterpretierbaren Beziehung.  

•	Es gibt prinzipiell zwei verschiedenen Submodel Modelle eine für den Assettyp und einen für die Assetinstanz (Beispiel Typ kann für Properties Ranges angeben, für die Instanz gibt es dann konkrete Werte). Es sollten deshalb auch 2 Submodell, für ein konkretes Asset geben, die aufeinander verweisen. Die Unterscheidung wird maschineinterintertierbar, ob sich ein Submodel in einer AAS steckt, die auf ein Assettyp oder Assetinstanz verweist. Das ist wieder eine implizite Beziehungsart. 
 es müsst eine semantische, d.h. maschineinterpretierbare Identifikation geben, ob ein Submodel für Typ oder Instanz gültig ist

Submodel Template Versionierung
o	Die Versionierung bei einem Template ist zwingend erforderlich und sollte am Ende der SemanticId erfolgen
o	Verallgemeinerung: müsste nicht bei allen Referenzen eine Version mitgegeben werden können?  
o	Vorschläge IRI wie IRDI mit Version/Revision ausstatten
•	In die ReferenzType Definition Version/Revision aufnehmen
•	 Version/Revision in die IRI strukturell aufnehmen 

Können Template Submodels und Instanz-Submodels gemischt in einer AAS liegen? Oder müssen Template und Instanz AAS hinsichtlich Template-Submodel getrennt modelliert werden. 
o	Mischung von Template und Instanzen in einer AAS dann sinnvoll, wenn es ein spezifische Submodel gibt  es ist also erlaubt
o	Ziel sollte es sein so viel Temlate Submodel wie möglich allgemein zur Verfügung zustellen, dann wäre ein Separierung von Template- und Instanz Submodels besser
o	Template Submodels können in einem SM Repository liegen  wie und wo ein solches Repository liegt ist noch nicht geklärt

•	Wie benennt man (idShort) bei mehrerer Instanzen eines Submodelelements in einer AAS?
o	idShort ist nur referable. Bei identifiable elemente dürfen in einer AAS idShorts mehrfach verwendet werden 
o	es ist nur für das Lesen von Menschen von Bedeutung 
o	hier brauchen wir eine best practice Regel 

•	In der genutzten Version des Package Explorers können Assets fälschlicherweise nur als Template/Instanz angelegt werden. Dies scheint ein Bug zu sein, da nach Metamodell Assets vom Kind „Type“ oder Kind „Instanz“ sind. 

Wie wird eine eclass – Klasse in der semanicId referenziert? Z.B. 
  | 23-11-01-19   Maschinenschraube mit Kopf ohne Antrieb [AAW994017]

**Comment by BirgitBoss** [comment]
Bzgl. des Bugs zu assetKind habe ich einen Bug im package explorer angelegt: https://github.com/admin-shell-io/aasx-package-explorer/issues/241

**Comment by BirgitBoss** [comment]
Bzgl. Frage "Wie wird eine eclass – Klasse in der semanicId referenziert?"
Warum soll da anders als bei Properties sein? Einfach die komplette IRDI angeben wie auch bei Properties. 

Das Beispiel " | 23-11-01-19 Maschinenschraube mit Kopf ohne Antrieb [AAW994017]" zeigt den Code (letzter Teil) und wohl den preferred name und zusätzlich noch die Klasse darüber (ganz vorne)?
Möchte man nicht die ganze Hierarchie modellieren, kann man in der semanticId auch zwei IRDIs eingeben (Reihenfolge wichtig!)

**Comment by BirgitBoss** [comment]
Ich verstehe die Anforderung "es müsst eine semantische, d.h. maschineinterpretierbare Identifikation geben, ob ein Submodel für Typ oder Instanz gültig ist" - allerdings: gilt nicht allgemeiner, dass für jedes Submodel-Template irgendwie klar sein müßte, für welche Art Assets es geeignet ist? Type und Instances eines Assets ist da nur ein spezieller Fall davon.
Interessant wäre zu wissen, welche weiteren Schlussfolgerungen eine Anwendung aus dieser Info ziehen kann... Ideen?

**Comment by BirgitBoss** [comment]
Versionierung beim Submodel-Template: vollkommen richtig, sollten wir so empfehlen!

https://github.com/admin-shell-io/questions-and-answers#id18
Die Frage ist, ob unsere Beispiele hier, die alle keine Versionierung haben, aktualisiert werden sollen?

**Comment by BirgitBoss** [comment]
Best practice bei "**(idShort) bei mehrerer Instanzen eines Submodelelements*: einfach nur durchnummerien wäre eine. Die andere wäre, es abhängig vom Submodel-Template zu machen, da die Elemente manchmal auch andere semantiken haben wie hinten-links, hinten-rechts usw. Ganz pauschal kann man das also nicht sagen.

**Comment by BirgitBoss** [comment]
Können Template Submodels und Instanz-Submodels gemischt in einer AAS liegen? 
Die Spec verbietet es nicht. Im Ziel wird es aber wie du schreibst, Submodel Template Repositories geben, von den die Submodel-instanzen abgeleitet werden können.

**Comment by BirgitBoss** [comment]
For the different questions separate issues were created (#13, #14, #15, #16 and #17 and  admin-shell-io/aasx-package-explorer#241 ) for better maintainability and tracking.
Please use these seaprates issues for further commenting. Please feel free to add comment and suggestions to these issues. 
If I missed something please feel free to either reopen this issue or directly add a separate issue. Thanks a lot!
