### ISSUE TITLE
How to know compliance/profile of an AAS Server Interface

### ISSUE THREAD

**Issue by egekorkan** [admin-shell-io/questions-and-answers#71]
The [specification](https://www.plattform-i40.de/IP/Redaktion/EN/Downloads/Publikation/Details_of_the_Asset_Administration_Shell_Part2_V1.html) of the AAS Server interface mentions:

> Another deployment example is the deployment of many AAS in an AAS repository. In such case the “Asset Administration Shell Repository Interface” may allow to create and manage multiple AAS in the repository. 
The separate interfaces of the HTTP/REST API allow many different ways to support such different deployments. A later version of this specification will define related profiles. 

From this, I understand that not all AAS Servers, even with the REST API, MUST implement the different resources and their operations. The fact that an HTTP GET request to https://admin-shell-io.com/51411/aas/submodels and https://admin-shell-io.com/51411/shells return `Route Not Found For GET /shells` and 404 sort of backs my understanding.

My main question is: Once someone gives me an AAS Server REST endpoint, how can I know what endpoints it supports? 

Side question: Is there any implementation of AAS Server that supports submodels?

**Comment by egekorkan** [comment]
I think that is fine and would be an issue belonging to the repository of the [AASXserver](https://github.com/admin-shell-io/aasx-server). However, my main point is that the spec allows different levels of implementation coverage via the profiles (which is not yet finalized). I think it would be necessary that the root endpoint of a server (like https://admin-shell-io.com/51411/) provides either an OpenAPI or a simple JSON Structure that conveys the information about implemented profiles. Maybe this should be an issue for the spec? If yes, do I open the issue at https://github.com/admin-shell-io/aas-specs/issues ?

**Comment by StenGruener** [comment]
cannot really judge it, afaik @aorzelskiGH has already started work to implement the "real" OpenAPI specification no the server

**Comment by StenGruener** [comment]
@egekorkan we are closing the issue for now, since we cannot fix/answer it in this group. Please feel free to update us on eventually opening an issue for the specification itself. @aorzelskiGH: let us discuss this one in the next group meeting briefly.
