### ISSUE TITLE
How to represent kinematic model for robotics

### ISSUE THREAD

**Issue by imcardle** [admin-shell-io/questions-and-answers#73]
Has a standard been proposed for the modelling of kinematics in AAS?  Common file formats for this information already exist (e.g. URDF files) - so perhaps the intention is for this information to simply be referenced or added as supplementary files in the AAS?  In any case, some guidance on the best practice would be useful, I think.

**Comment by StenGruener** [comment]
@imcardle: we are not aware of any dedicated kinematic models within AAS. 

However, if you are coming more from the simulation direction, the IDTA working group Simulation might be interesting for you. Here is one example: https://github.com/admin-shell-io/submodel-templates/blob/main/development/Simulation/1/0/Festo_VWS_DGST_8078833_16_02_2021_enl_1_FMU.aasx

On the other hand, embedding files within submodels is always possible using "File" submodel elements with dedicated semantic IDs, as it is, for example, done within the MTP submodel proposal.
