### ISSUE TITLE
AssetInformation References

### ISSUE THREAD

**Issue by felix-schubert** [admin-shell-io/questions-and-answers#78]
I have questions on creating the AssetAdminstrationShell.AssetInformation entities.

Given an asset with serial-number "SN-123" and an RFID identification of "0456" and a namespace "https://company.com/assets/".
globalAssetId should be a globally unique reference, hence composed of namespace and serial-number:
https://company.com/assets/SN-123

specificAssetId will be a SpecificAssetId for the serial number and a reference for the RFID:
{"name": "Serialnumber", "value": "SN-123", "externalSubjectId": **???**}
{"name": "RFID", "value": "0456", "externalSubjectId": **???**}

From 3.0RC02:
_The (external) subject the specific asset ID belongs to or has meaning to._ 

I do not understand, what values to use for externalSubjectId.

**Comment by BirgitBoss** [comment]
Not all specific IDs shall be visible to all users when looking up Asset Administration Shells. For example there typically is a manufacturer-part-ID, but several customer-part-IDs and only the customer shall be able to search for the digital twin via this specific asset ID.

The term "subject" is taken from ABAC (Attribute Based Access Control). It is assumed that the "subject" can be described by a unique ID.

**Comment by StenGruener** [comment]
@BirgitBoss: could you please provide a minimal example of a reference used for externalSubjectId? Also maybe some words regarding for access control-relevant usage (within Catena-X)?

**Comment by BirgitBoss** [comment]
In [Business Partner Data Management](https://catena-x.net/en/angebote/bpdm) each partner in the ecosystem Catena-X gets a unique ID, the so-called BPN (Business Partner Number). This BPN can then be used as value of externalSubjectId.

Info: the externalSubjectId will be optional in the next version of the specification. If empty the specific asset ID is visible to all having access to the registry.

**Comment by StenGruener** [comment]
@felix-schubert are you okay with the answer, Felix?

**Comment by StenGruener** [comment]
@felix-schubert

**Comment by felix-schubert** [comment]
Thank you.

**Comment by StenGruener** [comment]
Q: What values shall be used for externalSubjectId wihtin SpecificAssetId
A: Not all specific IDs shall be visible to all users when looking up Asset Administration Shells. For example there typically is a manufacturer-part-ID, but several customer-part-IDs and only the customer shall be able to search for the digital twin via this specific asset ID. The term "subject" is taken from ABAC (Attribute Based Access Control). It is assumed that the "subject" can be described by a unique ID.

**Comment by StenGruener** [comment]
fixed and to be published
