### ISSUE TITLE
How to describe the target Unit for phys_unit:conversionFactor?

### ISSUE THREAD

**Issue by changqin26** [admin-shell-io/questions-and-answers#84]
Hello, 

in the AAS Data Specification Physical Unit, we have the attribute - conversionFactor. The screenshot is the example from the Specification, where the unit "1/min" has a conversion factor 1.0/60. However, the target/output unit after applying this conversion factor is not indicated within this template. In other words, how should we express the actual meaning of this conversion factor? 

![image](https://user-images.githubusercontent.com/45127207/191272316-b2d83139-f592-4e84-9590-c517906ca64b.png)

**Comment by changqin26** [comment]
Hello @BirgitBoss, may you have a clue to this question?

**Comment by BirgitBoss** [comment]
I am not really an expert on physical unit and its conversions. Probably the confusion arises from the fact that one additionally needed data specification for quantities is not (yet) offered to completely describe the semantics of a physical unit.
In the example you need to refer to the ECLASS dictionary and Wiki for this missing information.

**Comment by changqin26** [comment]
Thanks for the hint, our customer has a clue to solve it now. We can close this issue.

**Comment by StenGruener** [comment]
@changqin26 any insights you could share?

**Comment by changqin26** [comment]
@StenGruener A new attribute of Physical Unit called "targetUnit" will be added and point to the IRDI of the target unit in Eclass or in CDD.
