### ISSUE TITLE
Add Guidance for Code Generation

### ISSUE THREAD

**Issue by sebbader-sap** [admin-shell-io/questions-and-answers#95]
The OpenAPI files are usually not manually translated into executable code but through the help of code generators. We are aware that some work pretty well, others somehow, and then there is a number of generators which just produce nonsense - if at all. We should add a section explaining the current state as far as we are aware of it, and document known issues and maybe even recommend one or two alternatives for the most important use cases.

Furthermore:
* the AAS community will *not* support anything, that's in the responsibility of the generator communities
* the described state might only be valid for very defined versions of the API and the generators --> the community as a whole needs to work together to keep the descriptions up to date.

**Comment by sebbader-sap** [comment]
Let's prepare an answer in this branch: https://github.com/admin-shell-io/questions-and-answers/tree/95-code-generation

**Comment by sebbader-sap** [comment]
@alexgordtop @noheton please add your findings as well.

**Comment by StenGruener** [comment]
ping

**Comment by sebbader-sap** [comment]
Hi Sten, doesn't look like anything has changed since July :-).

@alexgordtop @noheton can you please add your findings in the mentioned branch?

**Comment by StenGruener** [comment]
@sebbader-sap @alexgotdtop @noheton ping

**Comment by sebbader-sap** [comment]
I am not using any code generators for OpenAPI. Can anyone who does give a few insights?

**Comment by sebbader-sap** [comment]
Did anything change in the meantime? Did the generators become better, for instance?

**Comment by StenGruener** [comment]
no updates from participants, closing for now. @sebbader-sap feel free to re-open once you get new insights
