### ISSUE TITLE
Is there a consistent approach to mapping a classification of assets in the AAS?

### ISSUE THREAD

**Issue by foprs** [admin-shell-io/questions-and-answers#96]
In the "Generic Frame for Technical Data for Industrial Equipment in Manufacturing" (IDTA 02003), a guideline for the creation of submodel templates for technical data of assets, for example, the SubmodelElementCollection ProductClassifications is described. Would not be a classification of assets also in AssetInformation usefull for every kind of Asset?

**Comment by StenGruener** [comment]
This is out of scope of the working group, we are not able to change the metamodel. Feel free to reopen.

**Comment by foprs** [comment]
I am reopening because the information might be interesting for others as well:

- Which working group is maintaining this question-and-answers repo and what topics can be adressed here?
- Is there a repo to place issues/ideas for the metamodel existing?

**Comment by StenGruener** [comment]
1) we (group IDTA-workstream "Best modeling practice" are maintaining it, our self-understanding is to remove ambiguities while modeling, e.g. creating SM templates, but not changing the meta-model itself
2) https://github.com/admin-shell-io/aas-specs/issues would be the proper place
