### ISSUE TITLE
Is there a consistent approach to mapping cardinalities?

### ISSUE THREAD

**Issue by foprs** [admin-shell-io/questions-and-answers#97]
The mapping of cardinality is currently not specified. In many submodels, a qualifier is currently used for this purpose. What is the standard here?

**Comment by StenGruener** [comment]
hi Forps,

is your use-case submodel tempate? A more or less "hard" reference: to qualifier types is here: https://industrialdigitaltwin.org/wp-content/uploads/2022/12/I40-IDTA-WS-Process-How-to-write-a-SMT-FINAL-.pdf

![image](https://github.com/admin-shell-io/questions-and-answers/assets/69786685/0b9bd111-8d07-44f4-802b-6dc87088d3b7)

**Comment by foprs** [comment]
Yes, the use case is a SMT. Thank you for the answer!
