### ISSUE TITLE
How are enumerations mapped as values, e.g. of properties?

### ISSUE THREAD

**Issue by foprs** [admin-shell-io/questions-and-answers#98]
The specification (up to version 3-0) does not contain any specification for this. One way could be to map enumerations via ConceptDescriptions? What is best practice here?

**Comment by StenGruener** [comment]
do you mean value ids?

![image](https://github.com/admin-shell-io/questions-and-answers/assets/69786685/48499b89-9909-4499-a122-b4f5be4a0b20)

Do you have an example here, s.t. we could understand the problem betteR?

**Comment by foprs** [comment]
In between AAS Spec. V3 has been released. Enumaration can be modeled by SubmodelElementLists know (5.3.7.17).

**Comment by StenGruener** [comment]
not sure if it fits, can you haven an example for us here?

**Comment by foprs** [comment]
I would like to model that a value of a property is restricted to defined options. For example property 'color' with allowed values 'red', 'green' or 'yellow'.

**Comment by jh-isw** [comment]
@foprs [https://github.com/admin-shell-io/questions-and-answers#idgh77](https://github.com/admin-shell-io/questions-and-answers#idgh77) should be the exact answer.
