### ISSUE TITLE
Why is it possible to provide multiple keys in a ModelReference, e.g. when referencing a submodel from the AssetAdministrationShell?

### ISSUE THREAD

**Issue by JoergNeidig** [admin-shell-io/questions-and-answers#99]
What does it mean, if a ModelReference has multiple keys?
Is there one "main" key? If so, is it the first one in the list?
Usually keys/ids are used to identify an element. Does it even make sense to have more than one (sometimes it might make sense if the reference stores semantic information and no IDs)?

**Comment by StenGruener** [comment]
maybe Section 5.7.10.4 is relevant

**Comment by arnoweiss** [comment]
For referencing a Submodel from an AAS, you indeed just need one key. However, if referring to a SubmodelElement from a ReferenceElement, you need to concatenate more keys to the unique id to construct the path to the desired SubmodelElement. See [example](https://github.com/admin-shell-io/questions-and-answers/issues/103#issuecomment-1878939371)

A bunch of the examples online are wrong unfortunately and the whole referencing mechanism in the AAS is at best clumsy.

**Comment by StenGruener** [comment]
@JoergNeidig  2024-01-15 is ist sill relevant, or can it be merged with #103

**Comment by JoergNeidig** [comment]
Topic is still relevant, but should be merged with #103, because good examples could answer both questions.

**Comment by StenGruener** [comment]
Goes into #103
